export const googleFonts = [
  "Abel",
  "Abril Fatface",
  "Alegreya",
  "Alegreya Sans",
  "Amatic SC",
  "Anton",
  "Archivo",
  "Archivo Black",
  "Arimo",
  "Arvo",
  "Asap",
  "Assistant",
  "Balsamiq Sans",
  "Barlow",
  "Barlow Condensed",
  "Bebas Neue",
  "Bitter",
  "Cabin",
  "Cairo",
  "Catamaran",
  "Caveat",
  "Cinzel",
  "Comfortaa",
  "Cormorant Garamond",
  "Crimson Text",
  "Dancing Script",
  "DM Sans",
  "Dosis",
  "EB Garamond",
  "Exo 2",
  "Fira Sans",
  "Fjalla One",
  "Francois One",
  "Fredoka One",
  "Heebo",
  "Hind",
  "Hind Madurai",
  "Hind Siliguri",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Serif",
  "Inconsolata",
  "Indie Flower",
  "Inter",
  "Josefin Sans",
  "Jost",
  "Kanit",
  "Karla",
  "Lato",
  "Lexend",
  "Lexend Deca",
  "Libre Baskerville",
  "Libre Franklin",
  "Lobster",
  "Lora",
  "Macondo",
  "Manrope",
  "Merriweather",
  "Merriweather Sans",
  "Montserrat",
  "Montserrat Alternates",
  "Mukta",
  "Mulish",
  "Nanum Gothic",
  "Noto Sans TC",
  "Noto Serif TC",
  "Nunito",
  "Nunito Sans",
  "Open Sans",
  "Oswald",
  "Outfit",
  "Overpass",
  "Oxygen",
  "Pacifico",
  "Permanent Marker",
  "Play",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Prompt",
  "PT Sans",
  "PT Sans Narrow",
  "PT Serif",
  "Public Sans",
  "Quicksand",
  "Rajdhani",
  "Raleway",
  "Red Hat Display",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Mono",
  "Roboto Slab",
  "Rubik",
  "Shadows Into Light",
  "Sora",
  "Source Code Pro",
  "Source Sans Pro",
  "Source Serif Pro",
  "Space Grotesk",
  "Space Mono",
  "Syne",
  "Tajawal",
  "Teko",
  "Titillium Web",
  "Ubuntu",
  "Ubuntu Condensed",
  "Varela Round",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Zilla Slab"
];

export function getGoogleFontUrl(fontFamily: string): string {
  if (!fontFamily || fontFamily === "inherit" || fontFamily === "Default Font" || fontFamily === "Default") {
    return "";
  }

  // Format font name for Google Fonts API (e.g. "Noto Sans TC" -> "Noto+Sans+TC")
  const formattedName = fontFamily.replace(/ /g, "+");
  return `https://fonts.googleapis.com/css2?family=${formattedName}:wght@400;500;600;700;800;900&display=swap`;
}
